###
POST http://localhost:3000/projetos/
Content-Type: application/json

{
      "titulo": "Projeto 3",
      "descricao": "Descrição da projeto 3",
      "periodo": 2,
      "cursos": "1, 4, 5",
      "cr": 8.0
}

###
PUT http://localhost:3000/projetos/1
Content-Type: application/json

{
      "titulo": "Projeto 2",
      "descricao": "Descrição da projeto 2",
      "periodo": 5,
      "cursos": "6, 8, 12",
      "cr": 6.0
}


###
GET http://localhost:3000/projetos/

###
GET http://localhost:3000/projetos/2

###
DELETE  http://localhost:3000/projetos/1






###
POST http://localhost:3000/professores/
Content-Type: application/json

{   
      "cpf": "12345678910",
      "nome": "Campos",
      "email": "campos@gmail.com",
      "senha": "senha123"
}

###
PUT http://localhost:3000/professores/2
Content-Type: application/json

{   
      "cpf": "12345678910",
      "nome": "Eduardo",
      "email": "eduardo@gmail.com",
      "senha": "senha123"
}

###
GET http://localhost:3000/professores/

###
GET http://localhost:3000/professores/2

###
DELETE  http://localhost:3000/professores/2